export const GROUPS = {
  NT: { id: "NT", name: "分析家", hint: "偏苦、偏干" },
  NF: { id: "NF", name: "外交家", hint: "偏香、偏花" },
  SJ: { id: "SJ", name: "守护者", hint: "偏甜、偏稳" },
  SP: { id: "SP", name: "探险家", hint: "偏鲜、带气" },
};

export const COCKTAILS = [
  {
    type: "INTJ",
    group: "NT",
    name: "烟熏浓缩",
    who: "话少、脑子里有计划的人",
    why: "苦、干净、没什么装饰。跟这种人聊天也是这样。",
    when: "一个人想事情，不想被打扰",
    base: "梅斯卡尔 + 咖啡",
    recipe: ["烟熏梅斯卡尔", "冷萃咖啡", "黑芝麻酒", "苦精 2 滴"],
    taste: { sweet: 1, sour: 1, bitter: 5, strong: 5, fizz: 0 },
    color: "#4a2a16",
    glow: "#c48a48",
    glass: "rocks",
    ice: true,
    garnish: "orange",
    flavors: ["咖啡", "烟熏"],
    house: false,
  },
  {
    type: "INTP",
    group: "NT",
    name: "柚子马天尼",
    who: "想很多、不一定说出来的人",
    why: "干、带盐、有点酸。喝完还想再琢磨一口。",
    when: "半夜还开着一堆网页",
    base: "金酒 + 柚子",
    recipe: ["伦敦干金", "柚子皮", "干味美思", "海盐一撮"],
    taste: { sweet: 1, sour: 3, bitter: 3, strong: 4, fizz: 0 },
    color: "#d5deba",
    glow: "#b4c48a",
    glass: "nick",
    ice: false,
    garnish: "lime",
    flavors: ["柚子", "盐"],
    house: false,
  },
  {
    type: "ENTJ",
    group: "NT",
    name: "血橙波本",
    who: "做事快、喜欢拍板的人",
    why: "烈、热、有辣椒。一口就能醒神。",
    when: "要赶工、要做决定",
    base: "波本 + 血橙",
    recipe: ["波本威士忌", "血橙汁", "辣椒蜜", "橙苦精"],
    taste: { sweet: 2, sour: 3, bitter: 2, strong: 5, fizz: 0 },
    color: "#c44a22",
    glow: "#e87838",
    glass: "rocks",
    ice: true,
    garnish: "chili",
    flavors: ["血橙", "辣椒"],
    house: false,
  },
  {
    type: "ENTP",
    group: "NT",
    name: "姜汁气泡",
    who: "爱抬杠、也爱把场子带起来的人",
    why: "甜里带辣，还有气泡。喝一口换一个话题。",
    when: "还没想好去哪，但已经出门了",
    base: "朗姆 + 百香果 + 姜",
    recipe: ["白朗姆", "百香果", "鲜姜汁", "苏打水"],
    taste: { sweet: 3, sour: 3, bitter: 1, strong: 3, fizz: 5 },
    color: "#e8b43a",
    glow: "#f0d068",
    glass: "highball",
    ice: true,
    garnish: "lime",
    flavors: ["姜", "百香果"],
    house: false,
  },
  {
    type: "INFJ",
    group: "NF",
    name: "茉莉金菲士",
    who: "看着淡、其实很有主见的人",
    why: "花香、微甜、颜色很浅。要喝进去才知道味道。",
    when: "想安静坐一会儿，不想大声说话",
    base: "茉莉金酒 + 桂花",
    recipe: ["茉莉金酒", "桂花糖浆", "蜂蜜少许", "汤力水"],
    taste: { sweet: 2, sour: 2, bitter: 1, strong: 2, fizz: 3 },
    color: "#e6d4a4",
    glow: "#f0e2b8",
    glass: "coupe",
    ice: false,
    garnish: "flower",
    flavors: ["茉莉", "桂花"],
    house: true,
  },
  {
    type: "INFP",
    group: "NF",
    name: "荔枝玫瑰",
    who: "心思细、容易心软的人",
    why: "粉的、香的、喝到后面有一点涩。",
    when: "下雨刚停，还不想回家",
    base: "玫瑰酒 + 荔枝",
    recipe: ["玫瑰酒", "荔枝汁", "接骨木花", "苏打水"],
    taste: { sweet: 4, sour: 2, bitter: 1, strong: 2, fizz: 3 },
    color: "#f0b8c6",
    glow: "#f6c8d4",
    glass: "coupe",
    ice: false,
    garnish: "berry",
    flavors: ["玫瑰", "荔枝"],
    house: false,
  },
  {
    type: "ENFJ",
    group: "NF",
    name: "肉桂热朗姆",
    who: "总在照顾别人的人",
    why: "热的、甜的、有肉桂。喝完身子会暖起来。",
    when: "把大家都安顿好，终于轮到自己",
    base: "陈年朗姆 + 肉桂",
    recipe: ["陈年朗姆", "肉桂糖浆", "橙皮", "枫糖"],
    taste: { sweet: 4, sour: 1, bitter: 1, strong: 4, fizz: 0 },
    color: "#c86828",
    glow: "#e09048",
    glass: "rocks",
    ice: false,
    garnish: "cinnamon",
    flavors: ["肉桂", "橙皮"],
    house: false,
  },
  {
    type: "ENFP",
    group: "NF",
    name: "芒果辣椒玛格",
    who: "一来就把气氛带起来的人",
    why: "芒果甜，辣椒咸，颜色很亮。很好拍，也好喝。",
    when: "朋友说只坐五分钟，结果坐到打烊",
    base: "龙舌兰 + 芒果",
    recipe: ["龙舌兰", "芒果泥", "青柠", "辣椒盐杯口"],
    taste: { sweet: 4, sour: 3, bitter: 0, strong: 3, fizz: 1 },
    color: "#f07828",
    glow: "#ffb060",
    glass: "rocks",
    ice: true,
    garnish: "chili",
    flavors: ["芒果", "辣椒"],
    house: false,
  },
  {
    type: "ISTJ",
    group: "SJ",
    name: "核桃老式",
    who: "守时、靠谱、不爱变来变去的人",
    why: "经典威士忌，核桃和枫糖。配方固定，冰块两块。",
    when: "结束一天，把事情收整齐",
    base: "威士忌 + 核桃",
    recipe: ["纯麦威士忌", "核桃酒", "枫糖", "橙苦精"],
    taste: { sweet: 2, sour: 0, bitter: 3, strong: 5, fizz: 0 },
    color: "#6a3a18",
    glow: "#b07838",
    glass: "rocks",
    ice: true,
    garnish: "orange",
    flavors: ["核桃", "威士忌"],
    house: false,
  },
  {
    type: "ISFJ",
    group: "SJ",
    name: "香草奶酒",
    who: "默默把人都照顾好的人",
    why: "牛奶、香草、蜂蜜。软，不难喝，也不冲。",
    when: "需要被接住，又不想解释太多",
    base: "牛奶潘趣 + 香草",
    recipe: ["牛奶潘趣", "香草", "蜂蜜", "肉豆蔻"],
    taste: { sweet: 5, sour: 0, bitter: 0, strong: 2, fizz: 0 },
    color: "#f0e0c0",
    glow: "#f6ead0",
    glass: "coupe",
    ice: false,
    garnish: "cinnamon",
    flavors: ["牛奶", "香草"],
    house: false,
  },
  {
    type: "ESTJ",
    group: "SJ",
    name: "橙皮咖啡威士忌",
    who: "清单还没划完的人",
    why: "咖啡加威士忌，有盐，不拖泥带水。",
    when: "事情还剩两件，但必须先喝一口",
    base: "黑麦 + 咖啡",
    recipe: ["黑麦威士忌", "咖啡利口酒", "橙皮", "盐"],
    taste: { sweet: 1, sour: 1, bitter: 4, strong: 5, fizz: 0 },
    color: "#4a2c20",
    glow: "#8a5a38",
    glass: "rocks",
    ice: true,
    garnish: "orange",
    flavors: ["咖啡", "橙皮"],
    house: false,
  },
  {
    type: "ESFJ",
    group: "SJ",
    name: "白桃气泡",
    who: "喜欢把人都叫到桌边的人",
    why: "桃子、罗勒、气泡。轻，好入口，适合碰杯。",
    when: "人还没到齐，杯子已经先碰过了",
    base: "普罗塞克 + 白桃",
    recipe: ["普罗塞克", "白桃汁", "罗勒", "柠檬皮"],
    taste: { sweet: 4, sour: 2, bitter: 0, strong: 2, fizz: 5 },
    color: "#f2c898",
    glow: "#f8d8b0",
    glass: "flute",
    ice: false,
    garnish: "peach",
    flavors: ["白桃", "气泡"],
    house: false,
  },
  {
    type: "ISTP",
    group: "SP",
    name: "黄瓜山葵",
    who: "话少、手很准的人",
    why: "冰的、绿的、有山葵。不加糖。",
    when: "不想聊天，只想喝一口干净的",
    base: "伏特加 + 黄瓜",
    recipe: ["冰镇伏特加", "黄瓜汁", "山葵", "青柠"],
    taste: { sweet: 0, sour: 3, bitter: 1, strong: 4, fizz: 0 },
    color: "#b8d8c4",
    glow: "#d0ead8",
    glass: "nick",
    ice: false,
    garnish: "cucumber",
    flavors: ["黄瓜", "山葵"],
    house: false,
  },
  {
    type: "ISFP",
    group: "SP",
    name: "紫醉",
    who: "先看颜、再看味道的人",
    why: "紫色，有花香和柠檬。颜色先到，味道随后。",
    when: "不想被分类，只想要好看的一杯",
    base: "紫罗兰酒 + 金酒",
    recipe: ["紫罗兰酒", "金酒", "柠檬汁", "黑莓"],
    taste: { sweet: 3, sour: 3, bitter: 1, strong: 3, fizz: 0 },
    color: "#7a4caa",
    glow: "#b888d8",
    glass: "coupe",
    ice: false,
    garnish: "berry",
    flavors: ["紫罗兰", "黑莓"],
    house: false,
  },
  {
    type: "ESTP",
    group: "SP",
    name: "菠萝烟熏玛格",
    who: "喜欢试一把的人",
    why: "菠萝甜，梅斯卡尔有烟，杯口是盐。喝得快。",
    when: "还没想好要不要加注，人已经往前倾了",
    base: "梅斯卡尔 + 菠萝",
    recipe: ["梅斯卡尔", "菠萝汁", "青柠", "盐边"],
    taste: { sweet: 3, sour: 3, bitter: 1, strong: 4, fizz: 0 },
    color: "#f0c040",
    glow: "#ffe078",
    glass: "rocks",
    ice: true,
    garnish: "lime",
    flavors: ["菠萝", "盐"],
    house: false,
  },
  {
    type: "ESFP",
    group: "SP",
    name: "覆盆子香槟",
    who: "喜欢亮相、也喜欢把场子撑住的人",
    why: "红的、有气泡、上面有薄荷。就是要好看。",
    when: "还要再拍一张，再碰一次杯",
    base: "香槟 + 覆盆子",
    recipe: ["香槟", "覆盆子", "薄荷", "金箔少许"],
    taste: { sweet: 4, sour: 2, bitter: 0, strong: 2, fizz: 5 },
    color: "#d02850",
    glow: "#f06080",
    glass: "flute",
    ice: false,
    garnish: "mint",
    flavors: ["覆盆子", "香槟"],
    house: false,
  },
];

export const QUESTIONS = [
  {
    axis: "EI",
    prompt: "去酒吧你坐哪？",
    a: { key: "E", label: "吧台中间", line: "跟调酒师和旁边的人都能聊。" },
    b: { key: "I", label: "角落卡座", line: "自己点一杯，少说话。" },
  },
  {
    axis: "SN",
    prompt: "你点酒先看什么？",
    a: { key: "S", label: "配料和度数", line: "基酒是什么，冰不冰，甜不甜。" },
    b: { key: "N", label: "名字好不好听", line: "好不好拍，喝完像什么感觉。" },
  },
  {
    axis: "TF",
    prompt: "酒不好喝怎么办？",
    a: { key: "T", label: "直接说", line: "哪里太甜、太淡，请他重做。" },
    b: { key: "F", label: "先喝着", line: "不想让调酒师难堪。" },
  },
  {
    axis: "JP",
    prompt: "你怎么点？",
    a: { key: "J", label: "想好再点", line: "选定一杯，不改了。" },
    b: { key: "P", label: "看心情", line: "先来一杯，不好再换。" },
  },
];

const BY_TYPE = Object.fromEntries(COCKTAILS.map((c) => [c.type, c]));

export function getCocktail(type) {
  return BY_TYPE[type] || null;
}

export function typeFromAnswers(answers) {
  const map = Object.fromEntries(answers.map((a) => [a.axis, a.key]));
  return `${map.EI || "I"}${map.SN || "N"}${map.TF || "F"}${map.JP || "J"}`;
}

export function hexToRgb(hex) {
  const n = hex.replace("#", "");
  return {
    r: parseInt(n.slice(0, 2), 16),
    g: parseInt(n.slice(2, 4), 16),
    b: parseInt(n.slice(4, 6), 16),
  };
}

export const TASTE_LABELS = [
  ["sweet", "甜"],
  ["sour", "酸"],
  ["bitter", "苦"],
  ["strong", "烈"],
  ["fizz", "气"],
];
